### ISSUE TITLE
feat: Keyboard Shortcuts

### ISSUE THREAD

**Issue by jdpatt** [capn-freako/PyBERT#112]
Traitsui allows the use of keyboard shortcuts thru "accelerators".  Everything that I see says the ButtonHandler should support them as well.  Try it out and/or alternatively try a menuBar.  https://docs.enthought.com/envisage/tasks_user_manual/menus.html

- Run "Ctrl + R"
- Quit "Ctrl + Q"
- Open Config "Ctrl + O"
- Save Config "Ctrl + S"
- Toggle Debug Mode "Ctrl + `"

```python
    handler=GlobalHandler(),
    menubar=MenuBar(
        Menu(
            Action(name="Load Config.", action="load_config_clicked", accelerator="Ctrl+O"),
            Action(name="Load Results", action="load_data_clicked"),
            Separator(),
            Action(name="Save Config.", action="save_config_clicked", accelerator="Ctrl+S"),
            Action(name="Save Results", action="save_data_clicked"),
            Separator(),
            # CloseAction, #! Unable to add due to https://github.com/enthought/traitsui/issues/1442
            name="&File",
        ),
        Menu(
            Action(
                name="Debug Mode",
                action="toggle_debug_clicked",
                accelerator="Ctrl+`",
                style="toggle",
                checked_when="debug == True",
            ),
            Action(
                name="Clear Reference Waveform(s)",
                action="clear_reference_clicked",
            ),
            name="&View",
        ),
        Menu(
            Action(name="Run", action="run_simulation_clicked", accelerator="Ctrl+R"),
            name="&Simulation"
        ),
        Menu(
            Action(name="Getting Started", action="getting_started_clicked"),
            Action(name="&About", action="show_about_clicked"),
            name="&Help",
        ),
```

**Comment by capn-freako** [comment]
Hi @jdpatt ,

I'm confused. Have you made this addition to the code and are asking someone to kick its tires, or are you suggesting that the above code snippet be added/tried?

Thanks,
-db

**Comment by jdpatt** [comment]
That was copied from my develop branch as my starting point.  I'll open a PR tonight for this and clearing reference waveforms (#113 ) since it is closely related and done for you to play with.  I still need to try your other toolkits but with qt, all things work.
