### ISSUE TITLE
Errors and Warnings when run Python -m install

### ISSUE THREAD

**Issue by nyctalope** [capn-freako/PyBERT#25]
I followed the instruction below using Anaconda2(64bit) 
**conda install enable
conda install traitsui
conda install chaco
conda install kiwisolver
conda install scipy
conda install Sphinx
conda install matplotlib
pip install PyBERT
python -m pybert**

Looks the installs are almost good except the last one when run "python -m pybert"
There are still several errors or warnings. Not sure if they are critical

C**:\python\Anaconda2\lib\site-packages\pybert-2.0.2-py2.7.egg\pybert\pybert.py:1139: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\python\Anaconda2\lib\site-packages\chaco\array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
C:\python\Anaconda2\lib\site-packages\traits\trait_handlers.py:1599: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if value in self.values:
C:\python\Anaconda2\lib\site-packages\chaco\image_data.py:190: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
Traceback (most recent call last):
  File "C:\python\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\pybert\__main__.py", line 3, in <module>
  File "C:\python\Anaconda2\lib\site-packages\traits\has_traits.py", line 2156, in configure_traits
    kind, handler, id, scrollable, args )
  File "C:\python\Anaconda2\lib\site-packages\traitsui\toolkit.py", line 245, in view_application
    raise NotImplementedError
NotImplementedError**

**Comment by capn-freako** [comment]
Would you, please, try this:

*conda install wxPython*


and let me know if that works?

Thanks!
-db

**Comment by capn-freako** [comment]
And would you also try this command, and send me the resultant output?

*conda list qt*


Thanks!
-db

**Comment by nyctalope** [comment]
I just installed Anaconda2.0 and wxPython (wxPython is then added into the
package lib of Anaconda2.0) and have not install any packages, then I run
command "conda list qt",

*(**C:\python\Anaconda2) C:\Users\longyan\Documents>conda list qt*
*# packages in environment at C:\python\Anaconda2:*
*#*
*pyqt                      5.6.0                    py27_0*
*qt                        5.6.0                     vc9_0  [vc9]*
*qtawesome                 0.3.3                    py27_0*
*qtconsole                 4.2.1                    py27_2*
*qtpy                      1.1.2                    py27_0*

**Comment by nyctalope** [comment]
My anaconda is Anaconda2-4.2.0-Windows-x86_64.exe
When run "conda install enable", looks some packages will be upgraded while
some downgraded.
Possibly QT has been downgraded....

*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install enable*
*Fetching package metadata .........*
*Solving package specifications: ..........*

*Package plan for installation in environment C:\python\Anaconda2:*

*The following packages will be downloaded:*

*    package                    |            build*
*    ---------------------------|-----------------*
*    conda-env-2.6.0            |                0          498 B*
*    numpy-1.10.4               |           py27_2         2.9 MB*
*    pyqt-4.10.4                |           py27_1        31.2 MB*
*    traits-4.5.0               |           py27_0         373 KB*
*    conda-4.2.13               |           py27_0         455 KB*
*    numexpr-2.6.0              |      np110py27_0         139 KB*
*    pyface-4.5.2               |           py27_0         736 KB*
*    scipy-0.17.1               |      np110py27_1        11.5 MB*
*    scikit-learn-0.17.1        |      np110py27_1         3.5 MB*
*    traitsui-4.5.1             |           py27_0         839 KB*
*    enable-4.5.1               |      np110py27_0         1.2 MB*
*    ------------------------------------------------------------*
*                                           Total:        52.9 MB*

*The following NEW packages will be INSTALLED:*

*    conda-env:    2.6.0-0*
*    enable:       4.5.1-np110py27_0*
*    pyface:       4.5.2-py27_0*
*    traits:       4.5.0-py27_0*
*    traitsui:     4.5.1-py27_0*

*The following packages will be UPDATED:*

*    conda:        4.2.9-py27_0       --> 4.2.13-py27_0*
*    scikit-learn: 0.17.1-np111py27_1 --> 0.17.1-np110py27_1*

*The following packages will be DOWNGRADED due to dependency conflicts:*

*    numexpr:      2.6.1-np111py27_0  --> 2.6.0-np110py27_0*
*    numpy:        1.11.1-py27_1      --> 1.10.4-py27_2*
*    pyqt:         5.6.0-py27_0       --> 4.10.4-py27_1*
*    scipy:        0.18.1-np111py27_0 --> 0.17.1-np110py27_1*

*Proceed ([y]/n)? y*

*Fetching packages ...*
*conda-env-2.6. 100% |###############################| Time: 0:00:00  83.00
kB/s*
*numpy-1.10.4-p 100% |###############################| Time: 0:00:01   2.43
MB/s*
*pyqt-4.10.4-py 100% |###############################| Time: 0:00:47 691.92
kB/s*
*traits-4.5.0-p 100% |###############################| Time: 0:00:00 561.96
kB/s*
*conda-4.2.13-p 100% |###############################| Time: 0:00:00 570.09
kB/s*
*numexpr-2.6.0- 100% |###############################| Time: 0:00:00 318.42
kB/s*
*pyface-4.5.2-p 100% |###############################| Time: 0:00:00 820.25
kB/s*
*scipy-0.17.1-n 100% |###############################| Time: 0:00:02   5.96
MB/s*
*scikit-learn-0 100% |###############################| Time: 0:00:01   2.45
MB/s*
*traitsui-4.5.1 100% |###############################| Time: 0:00:00 978.81
kB/s*
*enable-4.5.1-n 100% |###############################| Time: 0:00:00   1.31
MB/s*
*Extracting packages ...*
*[      COMPLETE      ]|##################################################|
100%*
*Unlinking packages ...*
*[pyqt                ]|#########################                         |
 50%*

**Comment by nyctalope** [comment]
*I was thinking the problem is caused by package version mismatch, but not
so sure....*

*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda list qt*
# packages in environment at C:\python\Anaconda2:
#
pyqt                      5.6.0                    py27_0
qt                        5.6.0                     vc9_0  [vc9]
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_2
qtpy                      1.1.2                    py27_0


*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install enable*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    numpy-1.10.4               |           py27_2         2.9 MB
    pyqt-4.10.4                |           py27_1        31.2 MB
    traits-4.5.0               |           py27_0         373 KB
    conda-4.2.13               |           py27_0         455 KB
    numexpr-2.6.0              |      np110py27_0         139 KB
    pyface-4.5.2               |           py27_0         736 KB
    scipy-0.17.1               |      np110py27_1        11.5 MB
    scikit-learn-0.17.1        |      np110py27_1         3.5 MB
    traitsui-4.5.1             |           py27_0         839 KB
    enable-4.5.1               |      np110py27_0         1.2 MB
    ------------------------------------------------------------
                                           Total:        52.9 MB

The following NEW packages will be INSTALLED:

    conda-env:    2.6.0-0
    enable:       4.5.1-np110py27_0
    pyface:       4.5.2-py27_0
    traits:       4.5.0-py27_0
    traitsui:     4.5.1-py27_0

The following packages will be UPDATED:

    conda:        4.2.9-py27_0       --> 4.2.13-py27_0
    scikit-learn: 0.17.1-np111py27_1 --> 0.17.1-np110py27_1

The following packages will be DOWNGRADED due to dependency conflicts:

    numexpr:      2.6.1-np111py27_0  --> 2.6.0-np110py27_0
    numpy:        1.11.1-py27_1      --> 1.10.4-py27_2
    pyqt:         5.6.0-py27_0       --> 4.10.4-py27_1
    scipy:        0.18.1-np111py27_0 --> 0.17.1-np110py27_1

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  83.00
kB/s
numpy-1.10.4-p 100% |###############################| Time: 0:00:01   2.43
MB/s
pyqt-4.10.4-py 100% |###############################| Time: 0:00:47 691.92
kB/s
traits-4.5.0-p 100% |###############################| Time: 0:00:00 561.96
kB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:00 570.09
kB/s
numexpr-2.6.0- 100% |###############################| Time: 0:00:00 318.42
kB/s
pyface-4.5.2-p 100% |###############################| Time: 0:00:00 820.25
kB/s
scipy-0.17.1-n 100% |###############################| Time: 0:00:02   5.96
MB/s
scikit-learn-0 100% |###############################| Time: 0:00:01   2.45
MB/s
traitsui-4.5.1 100% |###############################| Time: 0:00:00 978.81
kB/s
enable-4.5.1-n 100% |###############################| Time: 0:00:00   1.31
MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Unlinking packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%


*********************************************************
*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install traitsui*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    traits-4.6.0               |           py27_0         386 KB
    pyface-5.1.0               |           py27_0         767 KB
    traitsui-5.1.0             |           py27_0         861 KB
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be UPDATED:

    pyface:   4.5.2-py27_0 --> 5.1.0-py27_0
    traits:   4.5.0-py27_0 --> 4.6.0-py27_0
    traitsui: 4.5.1-py27_0 --> 5.1.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
traits-4.6.0-p 100% |###############################| Time: 0:00:03 109.79
kB/s
pyface-5.1.0-p 100% |###############################| Time: 0:00:00 861.89
kB/s
traitsui-5.1.0 100% |###############################| Time: 0:00:00 966.23
kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Unlinking packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%



*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install chaco*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pil-1.1.7                  |           py27_0         711 KB
    chaco-4.5.0                |      np110py27_0         873 KB
    ------------------------------------------------------------
                                           Total:         1.5 MB

The following NEW packages will be INSTALLED:

    chaco:        4.5.0-np110py27_0
    pil:          1.1.7-py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    numexpr:      2.6.1-np111py27_1  --> 2.6.0-np110py27_0
    numpy:        1.11.2-py27_0      --> 1.10.4-py27_2
    pyface:       5.1.0-py27_0       --> 4.5.2-py27_0
    pyqt:         5.6.0-py27_1       --> 4.10.4-py27_1
    scikit-learn: 0.18.1-np111py27_0 --> 0.17.1-np110py27_1
    scipy:        0.18.1-np111py27_0 --> 0.17.1-np110py27_1
    traits:       4.6.0-py27_0       --> 4.5.0-py27_0
    traitsui:     5.1.0-py27_0       --> 4.5.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
pil-1.1.7-py27 100% |###############################| Time: 0:00:01 597.73
kB/s
chaco-4.5.0-np 100% |###############################| Time: 0:00:00 969.16
kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Unlinking packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%

*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install kiwisolver*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    kiwisolver-0.1.3           |           py27_0          60 KB

The following NEW packages will be INSTALLED:

    kiwisolver: 0.1.3-py27_0

Proceed ([y]/n)? y

Fetching packages ...
kiwisolver-0.1 100% |###############################| Time: 0:00:00 203.25
kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%

*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install scipy*
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\python\Anaconda2:
#
scipy                     0.18.1              np111py27_0

*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install sphinx*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sphinx-1.5.1               |           py27_0         1.3 MB

The following packages will be UPDATED:

    sphinx: 1.4.6-py27_0 --> 1.5.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
sphinx-1.5.1-p 100% |###############################| Time: 0:00:00   1.44
MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Unlinking packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%


*(C:\python\Anaconda2) C:\Users\longyan\Documents>conda install matplotlib*
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\python\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-1.5.3           |      np111py27_1         6.1 MB

The following packages will be UPDATED:

    matplotlib: 1.5.3-np111py27_0 --> 1.5.3-np111py27_1
    pyqt:       4.10.4-py27_1     --> 5.6.0-py27_1

Proceed ([y]/n)? y

Fetching packages ...
matplotlib-1.5 100% |###############################| Time: 0:00:02   2.83
MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################|
100%
Unlinking packages ...
[      COMPLETE      ]|##################################################|
100%
Linking packages ...
[      COMPLETE      ]|##################################################|
100%



*(C:\python\Anaconda2) C:\Users\longyan\Documents>pip install pybert*
Collecting pybert
Requirement already satisfied (use --upgrade to upgrade): traits in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): enable in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): Sphinx in
c:\python\anaconda2\lib\site-packages\sphinx-1.5.1-py2.7.egg (from pybert)
Requirement already satisfied (use --upgrade to upgrade): traitsui in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): docutils in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): Pygments in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in
c:\python\anaconda2\lib\site-packages (from pybert)
Collecting PyIBIS-AMI>=2.0.3 (from pybert)
Requirement already satisfied (use --upgrade to upgrade): chaco in
c:\python\anaconda2\lib\site-packages (from pybert)
Requirement already satisfied (use --upgrade to upgrade): numpy in
c:\python\anaconda2\lib\site-packages (from enable->pybert)
Requirement already satisfied (use --upgrade to upgrade): PIL in
c:\python\anaconda2\lib\site-packages\pil (from enable->pybert)
Requirement already satisfied (use --upgrade to upgrade): pyface in
c:\python\anaconda2\lib\site-packages (from enable->pybert)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in
c:\python\anaconda2\lib\site-packages (from Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade):
snowballstemmer>=1.1 in c:\python\anaconda2\lib\site-packages (from
Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): babel!=2.0,>=1.3
in c:\python\anaconda2\lib\site-packages (from Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade):
alabaster<0.8,>=0.7 in c:\python\anaconda2\lib\site-packages (from
Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): imagesize in
c:\python\anaconda2\lib\site-packages (from Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): requests in
c:\python\anaconda2\lib\site-packages (from Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3.5
in c:\python\anaconda2\lib\site-packages (from Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in
c:\python\anaconda2\lib\site-packages (from Jinja2->pybert)
Collecting parsec (from PyIBIS-AMI>=2.0.3->pybert)
Requirement already satisfied (use --upgrade to upgrade): scipy in
c:\python\anaconda2\lib\site-packages (from PyIBIS-AMI>=2.0.3->pybert)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in
c:\python\anaconda2\lib\site-packages (from PyIBIS-AMI>=2.0.3->pybert)
Collecting empy (from PyIBIS-AMI>=2.0.3->pybert)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in
c:\python\anaconda2\lib\site-packages (from
babel!=2.0,>=1.3->Sphinx->pybert)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil
in c:\python\anaconda2\lib\site-packages (from
matplotlib->PyIBIS-AMI>=2.0.3->pybert)
Requirement already satisfied (use --upgrade to upgrade): cycler in
c:\python\anaconda2\lib\site-packages (from
matplotlib->PyIBIS-AMI>=2.0.3->pybert)
Requirement already satisfied (use --upgrade to upgrade):
pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in c:\python\anaconda2\lib\site-packages
(from matplotlib->PyIBIS-AMI>=2.0.3->pybert)
Installing collected packages: parsec, empy, PyIBIS-AMI, pybert
Successfully installed PyIBIS-AMI-2.0.4 empy-3.3.2 parsec-3.3 pybert-2.0.3
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip'
command.

(C:\python\Anaconda2) C:\Users\longyan\Documents>


*(C:\python\Anaconda2) C:\Users\longyan\Documents>python -m pybert*
Traceback (most recent call last):
  File "C:\python\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\python\Anaconda2\lib\site-packages\pybert\__main__.py", line 1,
in <module>
    from pybert import *
  File "C:\python\Anaconda2\lib\site-packages\pybert\pybert.py", line 60,
in <module>
    from traitsui.api    import View, Item, Group
  File "C:\python\Anaconda2\lib\site-packages\traitsui\api.py", line 36, in
<module>
    from .editors.api import ArrayEditor
  File
"C:\python\Anaconda2\lib\site-packages\traitsui\editors\__init__.py", line
23, in <module>
    from .api import ArrayEditor
  File "C:\python\Anaconda2\lib\site-packages\traitsui\editors\api.py",
line 24, in <module>
    from .code_editor import CodeEditor
  File
"C:\python\Anaconda2\lib\site-packages\traitsui\editors\code_editor.py",
line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File
"C:\python\Anaconda2\lib\site-packages\traitsui\editors\code_editor.py",
line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "C:\python\Anaconda2\lib\site-packages\traits\traits.py", line 522,
in __call__
    return self.maker_function( *args, **metadata )
  File "C:\python\Anaconda2\lib\site-packages\traits\traits.py", line 1236,
in Color
    return ColorTrait( *args, **metadata )
  File "C:\python\Anaconda2\lib\site-packages\traitsui\toolkit_traits.py",
line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "C:\python\Anaconda2\lib\site-packages\traitsui\toolkit.py", line
161, in toolkit
    _toolkit = _import_toolkit(toolkit_name)
  File "C:\python\Anaconda2\lib\site-packages\traitsui\toolkit.py", line
83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "C:\python\Anaconda2\lib\site-packages\traitsui\qt4\__init__.py",
line 18, in <module>
    import pyface.qt
  File "C:\python\Anaconda2\lib\site-packages\pyface\qt\__init__.py", line
44, in <module>
    % qt_api)
RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'

**Comment by capn-freako** [comment]
Okay, glad to hear you’re up and running!

Thanks for all the feedback,
-db
