### ISSUE TITLE
Add dual Dirac model tail fitting.

### ISSUE THREAD

**Issue by capn-freako** [capn-freako/PyBERT#3]
## Issue Description

Currently, the random jitter standard deviation is calculated by simply measuring the variance of the jitter remaining, after all other components have been removed, and taking the square root. This is not a particularly accurate way of estimating the random unbounded portion of the jitter and will cause extrapolation to low BER to be unreliable. We need to add fitting to a known analytical model, in order to improve this situation. I propose the "dual Dirac" model, just because it is so prevalent. Any other opinions?
## Suggested Approach
- In the _calc_jitter()_ function in the _pybert_util.py_ file, look at the code just above the _return_ statement. Note the simplistic way in which the random jitter standard deviation is calculated.
- Replace this code with _dual Dirac_ fitting code, instead.
## Hints
- Peruse the _NumPy_ and _SciPy_ libraries for functions, which might be helpful in curve fitting applications such as this one.

**Comment by leeooox** [comment]
When will the "dual Dirac" method implemented to PyBERT?

**Comment by MarkMarlett** [comment]
I'm looking into this Capn...

**Comment by capn-freako** [comment]
> I'm looking into this Capn...

Hi @MarkMarlett ,

I just made you the official assignee on this one.
Let me know if I need to change that.

Thanks,
-db

**Comment by capn-freako** [comment]
Hi @MarkMarlett ,

So, after researching this a bit I've learned:

1. The original, or "true", dual Dirac approach takes the _total_ jitter as its input.
But, that means that it is including the ISI jitter in its calculations of Pj, which seems wrong to me.

1. According to Ransom Stephens (See last paragraph on p.5 of [1].), the most accurate estimates of Rj come from measuring the variance of the _data independent_ jitter, after removing periodic components, via spectral analysis, which is exactly what I'm already doing in PyBERT.

So, now, I'm hesitant to simply replace what PyBERT is doing w/ a dual Dirac alternative, because I think it's going to be less accurate.
I'm now leaning towards _adding_ a dual Dirac analysis and reporting its results parenthetically in the PyBERT status bar; something like:

`Jitter (ps): Pj: 1.2 (1.5), Rj: 0.4 (0.6)`

Any thoughts on all of this?

Thanks,
-db

[1] [Stephens, R., _Jitter Analysis: The dual-Dirac Model, RJ/DJ, and Q-Scale_, Agilent white paper, 2004](https://www.keysight.com/us/en/assets/7018-01309/white-papers/5989-3206.pdf)

**Comment by MarkMarlett** [comment]
David
You are correct you need to fully remove the periodic elements and the isi
separately actually anything you can recognize and remove you should. The
result is the random jitter.

We can have a call it.

**Comment by capn-freako** [comment]
Well, this is very interesting:

<img width="1392" alt="PyBERT_Jitter_Annotated" src="https://github.com/capn-freako/PyBERT/assets/1047450/6fb62f34-dc7e-4b7b-ac40-41cd2539ae84">

Maybe, we should be using _total_ jitter for post-DFE dual-Dirac analysis?
