### ISSUE TITLE
Freq. Resp. of channel from file fails to plot

### ISSUE THREAD

**Issue by JEprime** [capn-freako/PyBERT#30]
Hi, 

When I put an impulse response into PyBERT from a csv file, it fails to plot the frequency response. However, all other outputs look OK.

Jason
![image](https://user-images.githubusercontent.com/33660182/32782733-5e94a002-c917-11e7-8925-dddd21f53b3d.png)

**Comment by capn-freako** [comment]
Hi Jason,

Thanks for reporting this issue!

I've played with this quite a bit, using many different channels I have available, and have concluded that there's something unique about the channel you're using, which is triggering this behavior. Are you able to post the *.CSV file you're using?

Thanks,
-db

**Comment by JEprime** [comment]
Hi David,

Yes, I can share them. Should I post them or send them directly?

Cheers,
Jason

**Comment by capn-freako** [comment]
Either way is fine.

Thanks!
-db

**Comment by JEprime** [comment]
Here you go!

Jason

**Comment by capn-freako** [comment]
I don’t see any attached file(s).
-db

**Comment by JEprime** [comment]
Does your email address accept csv files?

**Comment by capn-freako** [comment]
Yes, as far as I know.

**Comment by capn-freako** [comment]
Hi Jason,

I went back through the e-mail thread and found this file attached to a message you sent me on Nov. 13: _7m30awg.csv_. Is that the correct file? If so, I think the problem may be the magnitudes of the numbers in the second column. I'm assuming this is an impulse response, in which case its second column should have units **(V/s)**. I don't think there's any way these numbers could have those units. Here's a plot of that file:

![7m30awg](https://user-images.githubusercontent.com/1047450/33950142-75e29c7a-dfe0-11e7-8a49-28e7fd163f7c.png)

**Comment by JEprime** [comment]
Hi David,

Yes, that's a good file.

I obtained this impulse response from S-parameters by extrapolating a dc
point, enforcing symmetry, and doing an ifft.

The impulse response is unitless because it is a time domain transfer
function.

I'm not sure how exactly to convert this to volts/s. Do you have a method?

Thank you,
Jason


On Dec 13, 2017 11:36 AM, "David Banas" <notifications@github.com> wrote:

Hi Jason,

I went back through the e-mail thread and found this file attached to a
message you sent me on Nov. 13: *7m30awg.csv*. Is that the correct file? If
so, I think the problem may be the magnitudes of the numbers in the second
column. I'm assuming this is an impulse response, in which case its second
column should have units *(V/s)*. I don't think there's any way these
numbers could have those units. Here's a plot of that file:

[image: 7m30awg]
<https://user-images.githubusercontent.com/1047450/33950142-75e29c7a-dfe0-11e7-8a49-28e7fd163f7c.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/capn-freako/PyBERT/issues/30#issuecomment-351446814>,
or mute the thread

**Comment by capn-freako** [comment]
Just normalize it to the sample interval of your signal vector.

**Comment by JEprime** [comment]
In other words, divide by delta-t?

**Comment by capn-freako** [comment]
Yes.
