### ISSUE TITLE
pybert 2.4.1 does not install kiwisolver

### ISSUE THREAD

**Issue by bakrowork** [capn-freako/PyBERT#41]
I've succesfully installed pybert, with the following:
https://github.com/capn-freako/PyBERT/wiki/instant_gratification

Whoever the kiwisolver does not gets installed.

**Comment by capn-freako** [comment]
Yes, several others have reported this also.
This should fix your problem:

> conda install kiwisolver

-db

**Comment by capn-freako** [comment]
This has been fixed as of release _v2.4.4_.
