### ISSUE TITLE
Hover Help Not Working in PyBERT 3.1.1

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#56]
Hover help not working in PyBERT 3.1.1.  I'm using Anaconda3 2019.07.

**Comment by jdpatt** [comment]
All hover tooltips or just one or two?  System/Version?

OSX 10.14 seems to work without issue.

<img width="354" alt="Screen Shot 2019-09-28 at 8 22 19 AM" src="https://user-images.githubusercontent.com/14203439/65816453-c3226c80-e1c9-11e9-8a1a-4e4f7e133f69.png">

**Comment by dghan0219** [comment]
I'm using Windows 10 and none of the tooltips work on any tab.

**Comment by dghan0219** [comment]
Windows 7 has the same problem.

**Comment by jdpatt** [comment]
Seems to work on my W10 machine.

> conda list anaconda$
anaconda                  2019.07                  py37_0

**Comment by dghan0219** [comment]
I see it's working now for all three Windows 10 PCs that I have and the one Windows 7 PC.  I think I was hovering over the text description of the input box rather than the input box.
This issue can be closed.
