### ISSUE TITLE
PyBERT 3.1.1 Opens Beyond Windows Desktop Space

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#59]
PyBERT 3.1.1 opens so large that it extends beyond the top and bottom of the Windows Desktop.  The PyBERT window's banner can't be accessed to maximize, minimize, or resize the window unless I do that through Process Explorer.

**Comment by jdpatt** [comment]
I see that too. You can also use the Windows Key + Direction (Left, Right, Up, Down) to force it into view easily.

**Comment by capn-freako** [comment]
Fixed in v3.1.2.
