### ISSUE TITLE
IBIS-AMI Issues

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#69]
Same issue as #52, but with the IBIS-AMI file dialogs this time -- saving rather than opening.

Also, why are all the check boxes associated with the IBIS-AMI models inactive?

For the Config buttons, please display the help text that is in the IBIS-AMI file next to the option.  Also, it appears only adaptive parameters are configurable and not the manually adjusted parameters as those boxes allow no changes.

**Comment by capn-freako** [comment]
Hi Dennis,

Would you, please, pull the tx-rx-split branch from the main PyBERT GitHub repository and try running that version.
See if this issue is still pertinent when running that code, and let me know if so.

Thanks!
-db

**Comment by capn-freako** [comment]
Fixed in v3.3.0.
