### ISSUE TITLE
Peak limit for optimizing CTLE

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#74]
The CTLE optimizer seems to peak at 20 dB, but many devices have a limit of 10 dB.  A maximum limit would be nice so the DFE gets optimized within the CTLE capabilities.

**Comment by capn-freako** [comment]
I agree with this request and will schedule it for a coming update.

In the meantime, as a temporary work-around:

1. Run a co-optimization.
2. If you find the selected CTLE boost is above your max. value then set it to that max. value and re-run a Tx-only optimization.
