### ISSUE TITLE
PyBERT 3.3.0 not reading interconnect files

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyBERT#78]
Interconnect files are not being read as the valid flag is never checked and the native interconnect section is never unselected.  I've tried 4-port S-parameter files (mixed-mode and normal, Touchstone version 1.0), impulse response files, and step response files.

Once this is corrected, read the Zref and f_step from the S-parameter file automatically.

**Comment by capn-freako** [comment]
Closing, as this appears to be working now.
Please, reopen if you're still having trouble.
